# num1=int(input("enter first number:"))
# num2=int(input("enter second number:"))
# print("first number is :",num1)
# print("second number is :",num2)
# print(type(num1))
# print(type(num2))
# print(num1+num2)

num1=input("enter first number:")
num2=input("enter second number:")
print("first number is :",num1)
print("second number is :",num2)
print(type(num1))
print(type(num2))
print(num1+num2)
print(float(num1)+float(num2))
